### ISSUE TITLE
Allow underscores in security group rule names

### ISSUE THREAD

**Issue by liutaurasa** [terraform-ibm-modules/terraform-ibm-security-group#218]
### Description

Currently the validation rule in **terraform-ibm-security-group** module is:
`error_message = "Security group rule names must match the regex pattern ^([a-z]|[a-z][-a-z0-9]*[a-z0-9])$."`

Is there a particular reason to not include `_` (underscore)?
I'm working on introducing **terraform-ibm-security-group** module into an existing infrastructure created by terraform. Security groups are already created with underscores in their rule names.

### New or affected modules
terraform-ibm-security-group 

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
PR merged. Closing issue.

**Comment by ocofaigh** [comment]
@liutaurasa Can you try with https://github.com/terraform-ibm-modules/terraform-ibm-security-group/releases/tag/v2.3.1 ?
